"""
Phase 7: Control-First Baseline — Locked Reference Implementation

NOTE:
This file is intentionally isolated from:
- neuromorphic processing (Phase 2)
- energy harvesting models (Phase 4)
- recursive reflection (Phase 6)
- grounding or materials models (Phase 3, 5)

Those belong to later experimental phases and MUST NOT
be introduced until this baseline is validated or invalidated.

Purpose: Establish deterministic, falsifiable control baseline
for regression testing and architectural sanity checks.

Do not edit this file to add speculative features.
If experimental ideas arise, create a separate phase file.
"""

import numpy as np


# Deterministic, minimal baseline: input → PD → 2nd-order plant
# Outputs a history dict with keys: 't','L','theta_deg','omega','E','T'


def run_baseline(rng_seed: int = 0):
    rng = np.random.default_rng(rng_seed)

    # Config
    dt = 0.1
    N = 1000
    m, c, k = 1.0, 0.5, 1.0
    Kp, Kd = 0.3, 0.4

    # Time and input (light) — smooth + small noise, clipped to [0,1]
    t = np.arange(N) * dt
    L_base = 0.5 + 0.4 * np.sin(2 * np.pi * t / 20.0)
    L = np.clip(L_base + 0.03 * rng.standard_normal(N), 0.0, 1.0)

    # Plant state (radians)
    theta = np.deg2rad(90.0)  # start centered
    omega = 0.0

    # Recording
    theta_deg_hist = np.zeros(N)
    omega_hist = np.zeros(N)
    E_hist = np.zeros(N)
    T_hist = np.zeros(N)

    E = 50.0  # energy proxy [0,100]
    T = 25.0  # temperature proxy (deg C)

    for i in range(N):
        # Map light → angle setpoint in radians [0, pi]
        theta_sp = np.deg2rad(180.0) * L[i]

        # PD control in radians
        err = theta_sp - theta
        u = Kp * err - Kd * omega

        # 2nd-order plant: m*theta_dd + c*omega + k*theta = u
        theta_dd = (u - c * omega - k * theta) / m
        omega += theta_dd * dt
        theta += omega * dt

        # Proxies: simple bounded dynamics
        # energy goes down with control effort, up slightly per step
        E = np.clip(E + 0.02 - 0.002 * abs(u), 0.0, 100.0)
        # temperature rises with light and actuation, cools slightly
        T = T + 0.05 * (L[i] - 0.3) + 0.01 * abs(u) - 0.01 * (T - 25.0)

        theta_deg_hist[i] = np.rad2deg(theta)
        omega_hist[i] = omega  # radians per second (discrete step)
        E_hist[i] = E
        T_hist[i] = T

    return {
        "t": t,
        "L": L,
        "theta_deg": theta_deg_hist,
        "omega": omega_hist,
        "E": E_hist,
        "T": T_hist,
    }


if __name__ == "__main__":
    h = run_baseline(rng_seed=0)
    N = len(h["t"])
    print(f"N={N}, dt=0.1")
    print(
        f"theta_deg: min={h['theta_deg'].min():.3f}, max={h['theta_deg'].max():.3f}"
    )
    print(f"|omega|_max={np.abs(h['omega']).max():.3f} rad/step")
    print(f"E range: {h['E'].min():.3f}..{h['E'].max():.3f}")
    print(f"T range: {h['T'].min():.3f}..{h['T'].max():.3f}")
